// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSUYuiQtnjZ07Aq8ST9pHEv5sdsnv5VQ0',
    appId: '1:606607491454:web:3da645b9bbd7fb857df32f',
    messagingSenderId: '606607491454',
    projectId: 'movies-app-762b3',
    authDomain: 'movies-app-762b3.firebaseapp.com',
    storageBucket: 'movies-app-762b3.appspot.com',
    measurementId: 'G-6Y1E1Z6LR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-kOLr1RSVO-u5GWBhtwuRDL8QyTpJwrY',
    appId: '1:606607491454:android:0e73bec16dddbdd27df32f',
    messagingSenderId: '606607491454',
    projectId: 'movies-app-762b3',
    storageBucket: 'movies-app-762b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_C-jx76ZTBBlrCvSmuEz3MXM12BeL-NE',
    appId: '1:606607491454:ios:d5b035449874a7437df32f',
    messagingSenderId: '606607491454',
    projectId: 'movies-app-762b3',
    storageBucket: 'movies-app-762b3.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_C-jx76ZTBBlrCvSmuEz3MXM12BeL-NE',
    appId: '1:606607491454:ios:51da6dd3226d26287df32f',
    messagingSenderId: '606607491454',
    projectId: 'movies-app-762b3',
    storageBucket: 'movies-app-762b3.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
